[server]
directory = "server"
build_command = "cargo build"
run_command = "cargo run"

[endpoints]
bin_directory = "bin"
cgi_directory = "cgi"

[build_instructions]
# $FILE_NAME$ is the name of the file before the file extension
# $COPY$ is used for copying binary files directly into the bin directory
go = "go build -o $FILE_NAME$ $FILE_NAME$.go"
cpp = "g++ -o $FILE_NAME$ $FILE_NAME$.cpp"
c = "gcc -o $FILE_NAME$ $FILE_NAME$.c"
sh = "$COPY$"
